openapi: 3.0.1
info:
  title: STAT Copilot for Security Module
  description: This module is used to get enrich Sentinel incident using the Sentinel Triage Assistant (or STAT) version 2.
  version: 1.0.0
paths:
  /copilot:
    post:
      summary: Copilot endpoint
      description: |
        This module is used to enrich Sentinel incident and get information about the entitites from a Sentinel incident using the incident ARM ID as an input.
        # ExamplePrompts Can you enrich this incident using STAT?
        # ExamplePrompts Can you get more information about incident 1234 with STAT?
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CopilotModuleRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CopilotModuleResponse'
components:
  schemas:
    CopilotModuleRequest:
      type: object
      properties:
        incidentARMId:
          type: string
          description: |
            The Sentinel incident ARM Identifier (or incident ARM Id)It is not a number, it is an Azure Ressource Manager unique identifier.
    CopilotModuleResponse:
      type: object
      properties:
        username:
          type: string
          description: the username impacted by the incident
        riskLevel:
          type: string
          description: the level of risk in Entra ID Identity Protection of the user impacted by the incident 
        incidentARMId:
          type: string
          description: the ARM ID of the Sentinel incident, the information is not displayed unless specifically asked
        incidentNumber:
          type: integer
          description: the Sentinel incident number
